// HSK Vocabulary Data organized by levels
export const hskVocabularyData = {
  HSK1: [
    {
      id: 1,
      chinese: "你好",
      pinyin: "nǐ hǎo",
      vietnamese: "xin chào",
      english: "hello",
      example: "你好，很高兴见到你。",
      exampleTranslation: "Xin chào, rất vui được gặp bạn.",
      topic: "greetings",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/nihao.mp3"
    },
    {
      id: 2,
      chinese: "谢谢",
      pinyin: "xiè xiè",
      vietnamese: "cảm ơn",
      english: "thank you",
      example: "谢谢你的帮助。",
      exampleTranslation: "Cảm ơn sự giúp đỡ của bạn.",
      topic: "greetings",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/xiexie.mp3"
    },
    {
      id: 3,
      chinese: "我",
      pinyin: "wǒ",
      vietnamese: "tôi",
      english: "I, me",
      example: "我是学生。",
      exampleTranslation: "Tôi là học sinh.",
      topic: "pronouns",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/wo.mp3"
    },
    {
      id: 4,
      chinese: "的",
      pinyin: "de",
      vietnamese: "của",
      english: "of, possessive particle",
      example: "这是我的书。",
      exampleTranslation: "Đây là quyển sách của tôi.",
      topic: "grammar",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/de.mp3"
    },
    {
      id: 5,
      chinese: "你",
      pinyin: "nǐ",
      vietnamese: "bạn",
      english: "you",
      example: "你是老师吗？",
      exampleTranslation: "Bạn có phải là giáo viên không?",
      topic: "pronouns",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/ni.mp3"
    },
    {
      id: 6,
      chinese: "他",
      pinyin: "tā",
      vietnamese: "anh ấy",
      english: "he, him",
      example: "他是我的朋友。",
      exampleTranslation: "Anh ấy là bạn của tôi.",
      topic: "pronouns",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/ta.mp3"
    },
    {
      id: 7,
      chinese: "是",
      pinyin: "shì",
      vietnamese: "là",
      english: "to be",
      example: "我是中国人。",
      exampleTranslation: "Tôi là người Trung Quốc.",
      topic: "grammar",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/shi.mp3"
    },
    {
      id: 8,
      chinese: "不",
      pinyin: "bù",
      vietnamese: "không",
      english: "no, not",
      example: "我不是老师。",
      exampleTranslation: "Tôi không phải là giáo viên.",
      topic: "grammar",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/bu.mp3"
    },
    {
      id: 9,
      chinese: "这",
      pinyin: "zhè",
      vietnamese: "này",
      english: "this",
      example: "这是什么？",
      exampleTranslation: "Cái này là gì?",
      topic: "demonstratives",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/zhe.mp3"
    },
    {
      id: 10,
      chinese: "那",
      pinyin: "nà",
      vietnamese: "kia",
      english: "that",
      example: "那是我的车。",
      exampleTranslation: "Cái kia là xe của tôi.",
      topic: "demonstratives",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/na.mp3"
    },
    {
      id: 11,
      chinese: "什么",
      pinyin: "shén me",
      vietnamese: "gì, cái gì",
      english: "what",
      example: "你叫什么名字？",
      exampleTranslation: "Bạn tên là gì?",
      topic: "questions",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/shenme.mp3"
    },
    {
      id: 12,
      chinese: "哪",
      pinyin: "nǎ",
      vietnamese: "nào",
      english: "which",
      example: "你是哪国人？",
      exampleTranslation: "Bạn là người nước nào?",
      topic: "questions",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/na.mp3"
    },
    {
      id: 13,
      chinese: "水",
      pinyin: "shuǐ",
      vietnamese: "nước",
      english: "water",
      example: "我想喝水。",
      exampleTranslation: "Tôi muốn uống nước.",
      topic: "food",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/shui.mp3"
    },
    {
      id: 14,
      chinese: "茶",
      pinyin: "chá",
      vietnamese: "trà",
      english: "tea",
      example: "我喜欢喝茶。",
      exampleTranslation: "Tôi thích uống trà.",
      topic: "food",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/cha.mp3"
    },
    {
      id: 15,
      chinese: "吃",
      pinyin: "chī",
      vietnamese: "ăn",
      english: "to eat",
      example: "我们一起吃饭吧。",
      exampleTranslation: "Chúng ta cùng ăn cơm nhé.",
      topic: "food",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/chi.mp3"
    },
    {
      id: 16,
      chinese: "喝",
      pinyin: "hē",
      vietnamese: "uống",
      english: "to drink",
      example: "你喝什么？",
      exampleTranslation: "Bạn uống gì?",
      topic: "food",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/he.mp3"
    },
    {
      id: 17,
      chinese: "一",
      pinyin: "yī",
      vietnamese: "một",
      english: "one",
      example: "一个苹果。",
      exampleTranslation: "Một quả táo.",
      topic: "numbers",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/yi.mp3"
    },
    {
      id: 18,
      chinese: "二",
      pinyin: "èr",
      vietnamese: "hai",
      english: "two",
      example: "二十块钱。",
      exampleTranslation: "Hai mười đồng.",
      topic: "numbers",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/er.mp3"
    },
    {
      id: 19,
      chinese: "三",
      pinyin: "sān",
      vietnamese: "ba",
      english: "three",
      example: "三点钟。",
      exampleTranslation: "Ba giờ.",
      topic: "numbers",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/san.mp3"
    },
    {
      id: 20,
      chinese: "中国",
      pinyin: "zhōng guó",
      vietnamese: "Trung Quốc",
      english: "China",
      example: "我来自中国。",
      exampleTranslation: "Tôi đến từ Trung Quốc.",
      topic: "countries",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/zhongguo.mp3"
    },
    {
      id: 21,
      chinese: "人",
      pinyin: "rén",
      vietnamese: "người",
      english: "person, people",
      example: "他是好人。",
      exampleTranslation: "Anh ấy là người tốt.",
      topic: "people",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/ren.mp3"
    },
    {
      id: 22,
      chinese: "朋友",
      pinyin: "péng yǒu",
      vietnamese: "bạn bè",
      english: "friend",
      example: "我们是好朋友。",
      exampleTranslation: "Chúng tôi là bạn tốt.",
      topic: "people",
      hskLevel: "HSK1",
      difficulty: "beginner",
      audio: "/audio/pengyou.mp3"
    }
  ],
  HSK2: [
    {
      id: 23,
      chinese: "家庭",
      pinyin: "jiā tíng",
      vietnamese: "gia đình",
      english: "family",
      example: "我有一个幸福的家庭。",
      exampleTranslation: "Tôi có một gia đình hạnh phúc.",
      topic: "family",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/jiating.mp3"
    },
    {
      id: 24,
      chinese: "妈妈",
      pinyin: "mā ma",
      vietnamese: "mẹ",
      english: "mother",
      example: "我的妈妈很漂亮。",
      exampleTranslation: "Mẹ tôi rất xinh đẹp.",
      topic: "family",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/mama.mp3"
    },
    {
      id: 25,
      chinese: "爸爸",
      pinyin: "bà ba",
      vietnamese: "bố",
      english: "father",
      example: "我爸爸是医生。",
      exampleTranslation: "Bố tôi là bác sĩ.",
      topic: "family",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/baba.mp3"
    },
    {
      id: 26,
      chinese: "学校",
      pinyin: "xué xiào",
      vietnamese: "trường học",
      english: "school",
      example: "我在学校学习中文。",
      exampleTranslation: "Tôi học tiếng Trung ở trường.",
      topic: "education",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/xuexiao.mp3"
    },
    {
      id: 27,
      chinese: "老师",
      pinyin: "lǎo shī",
      vietnamese: "giáo viên",
      english: "teacher",
      example: "我的老师很好。",
      exampleTranslation: "Giáo viên của tôi rất tốt.",
      topic: "education",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/laoshi.mp3"
    },
    {
      id: 28,
      chinese: "学生",
      pinyin: "xué shēng",
      vietnamese: "học sinh",
      english: "student",
      example: "他是我的同学。",
      exampleTranslation: "Anh ấy là bạn cùng lớp của tôi.",
      topic: "education",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/xuesheng.mp3"
    },
    {
      id: 29,
      chinese: "学习",
      pinyin: "xué xí",
      vietnamese: "học tập",
      english: "to study",
      example: "我每天学习中文。",
      exampleTranslation: "Tôi học tiếng Trung mỗi ngày.",
      topic: "education",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/xuexi.mp3"
    },
    {
      id: 30,
      chinese: "工作",
      pinyin: "gōng zuò",
      vietnamese: "công việc",
      english: "work, job",
      example: "我的工作很忙。",
      exampleTranslation: "Công việc của tôi rất bận.",
      topic: "work",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/gongzuo.mp3"
    },
    {
      id: 31,
      chinese: "医生",
      pinyin: "yī shēng",
      vietnamese: "bác sĩ",
      english: "doctor",
      example: "我想当医生。",
      exampleTranslation: "Tôi muốn làm bác sĩ.",
      topic: "work",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/yisheng.mp3"
    },
    {
      id: 32,
      chinese: "时间",
      pinyin: "shí jiān",
      vietnamese: "thời gian",
      english: "time",
      example: "时间过得很快。",
      exampleTranslation: "Thời gian trôi qua rất nhanh.",
      topic: "time",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/shijian.mp3"
    },
    {
      id: 33,
      chinese: "今天",
      pinyin: "jīn tiān",
      vietnamese: "hôm nay",
      english: "today",
      example: "今天天气很好。",
      exampleTranslation: "Hôm nay thời tiết rất đẹp.",
      topic: "time",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/jintian.mp3"
    },
    {
      id: 34,
      chinese: "明天",
      pinyin: "míng tiān",
      vietnamese: "ngày mai",
      english: "tomorrow",
      example: "明天我要去北京。",
      exampleTranslation: "Ngày mai tôi sẽ đi Bắc Kinh.",
      topic: "time",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/mingtian.mp3"
    },
    {
      id: 35,
      chinese: "昨天",
      pinyin: "zuó tiān",
      vietnamese: "hôm qua",
      english: "yesterday",
      example: "昨天我看了电影。",
      exampleTranslation: "Hôm qua tôi đã xem phim.",
      topic: "time",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/zuotian.mp3"
    },
    {
      id: 36,
      chinese: "年",
      pinyin: "nián",
      vietnamese: "năm",
      english: "year",
      example: "我二十岁了。",
      exampleTranslation: "Tôi hai mười tuổi rồi.",
      topic: "time",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/nian.mp3"
    },
    {
      id: 37,
      chinese: "月",
      pinyin: "yuè",
      vietnamese: "tháng",
      english: "month",
      example: "这个月很忙。",
      exampleTranslation: "Tháng này rất bận.",
      topic: "time",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/yue.mp3"
    },
    {
      id: 38,
      chinese: "天",
      pinyin: "tiān",
      vietnamese: "ngày",
      english: "day",
      example: "一天有二十四小时。",
      exampleTranslation: "Một ngày có hai mười bốn giờ.",
      topic: "time",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/tian.mp3"
    },
    {
      id: 39,
      chinese: "钱",
      pinyin: "qián",
      vietnamese: "tiền",
      english: "money",
      example: "这个多少钱？",
      exampleTranslation: "Cái này bao nhiêu tiền?",
      topic: "shopping",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/qian.mp3"
    },
    {
      id: 40,
      chinese: "买",
      pinyin: "mǎi",
      vietnamese: "mua",
      english: "to buy",
      example: "我想买这个。",
      exampleTranslation: "Tôi muốn mua cái này.",
      topic: "shopping",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/mai.mp3"
    },
    {
      id: 41,
      chinese: "卖",
      pinyin: "mài",
      vietnamese: "bán",
      english: "to sell",
      example: "他卖水果。",
      exampleTranslation: "Anh ấy bán trái cây.",
      topic: "shopping",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/mai2.mp3"
    },
    {
      id: 42,
      chinese: "商店",
      pinyin: "shāng diàn",
      vietnamese: "cửa hàng",
      english: "shop, store",
      example: "这个商店很大。",
      exampleTranslation: "Cửa hàng này rất lớn.",
      topic: "shopping",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/shangdian.mp3"
    },
    {
      id: 43,
      chinese: "衣服",
      pinyin: "yī fú",
      vietnamese: "quần áo",
      english: "clothes",
      example: "我要买新衣服。",
      exampleTranslation: "Tôi muốn mua quần áo mới.",
      topic: "shopping",
      hskLevel: "HSK2",
      difficulty: "beginner",
      audio: "/audio/yifu.mp3"
    },
    {
      id: 44,
      chinese: "房子",
      pinyin: "fáng zi",
      vietnamese: "nhà",
      english: "house",
      example: "我们的房子很漂亮。",
      exampleTranslation: "Ngôi nhà của chúng tôi rất đẹp.",
      topic: "home",
      hskLevel: "HSK2",
      difficulty: "beginner",      audio: "/audio/fangzi.mp3"
    }
  ],
  HSK3: [
    {
      id: 45,
      chinese: "旅行",
      pinyin: "lǚ xíng",
      vietnamese: "du lịch",
      english: "travel",
      example: "我喜欢旅行。",
      exampleTranslation: "Tôi thích du lịch.",
      topic: "travel",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/luxing.mp3"
    },
    {
      id: 46,
      chinese: "飞机",
      pinyin: "fēi jī",
      vietnamese: "máy bay",
      english: "airplane",
      example: "我坐飞机去北京。",
      exampleTranslation: "Tôi đi máy bay đến Bắc Kinh.",
      topic: "travel",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/feiji.mp3"
    },
    {
      id: 47,
      chinese: "火车",
      pinyin: "huǒ chē",
      vietnamese: "tàu hỏa",
      english: "train",
      example: "火车很快。",
      exampleTranslation: "Tàu hỏa rất nhanh.",
      topic: "travel",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/huoche.mp3"
    },
    {
      id: 48,
      chinese: "汽车",
      pinyin: "qì chē",
      vietnamese: "ô tô",
      english: "car",
      example: "我开车上班。",
      exampleTranslation: "Tôi lái xe đi làm.",
      topic: "travel",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/qiche.mp3"
    },
    {
      id: 49,
      chinese: "自行车",
      pinyin: "zì xíng chē",
      vietnamese: "xe đạp",
      english: "bicycle",
      example: "我喜欢骑自行车。",
      exampleTranslation: "Tôi thích đi xe đạp.",
      topic: "travel",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/zixingche.mp3"
    },
    {
      id: 50,
      chinese: "游泳",
      pinyin: "yóu yǒng",
      vietnamese: "bơi lội",
      english: "swimming",
      example: "夏天我喜欢游泳。",
      exampleTranslation: "Mùa hè tôi thích bơi lội.",
      topic: "sports",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/youyong.mp3"
    },
    {
      id: 51,
      chinese: "跑步",
      pinyin: "pǎo bù",
      vietnamese: "chạy bộ",
      english: "running",
      example: "早上我去跑步。",
      exampleTranslation: "Sáng sớm tôi đi chạy bộ.",
      topic: "sports",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/paobu.mp3"
    },
    {
      id: 52,
      chinese: "踢足球",
      pinyin: "tī zú qiú",
      vietnamese: "đá bóng",
      english: "play football",
      example: "我们踢足球吧。",
      exampleTranslation: "Chúng ta đá bóng nhé.",
      topic: "sports",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/tizuqiu.mp3"
    },
    {
      id: 53,
      chinese: "打篮球",
      pinyin: "dǎ lán qiú",
      vietnamese: "chơi bóng rổ",
      english: "play basketball",
      example: "他很会打篮球。",
      exampleTranslation: "Anh ấy chơi bóng rổ rất giỏi.",
      topic: "sports",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/dalanqiu.mp3"
    },
    {
      id: 54,
      chinese: "音乐",
      pinyin: "yīn yuè",
      vietnamese: "âm nhạc",
      english: "music",
      example: "我喜欢听音乐。",
      exampleTranslation: "Tôi thích nghe nhạc.",
      topic: "entertainment",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/yinyue.mp3"
    },
    {
      id: 55,
      chinese: "电影",
      pinyin: "diàn yǐng",
      vietnamese: "phim",
      english: "movie",
      example: "这部电影很有趣。",
      exampleTranslation: "Bộ phim này rất thú vị.",
      topic: "entertainment",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/dianying.mp3"
    },
    {
      id: 56,
      chinese: "书",
      pinyin: "shū",
      vietnamese: "sách",
      english: "book",
      example: "我在看一本好书。",
      exampleTranslation: "Tôi đang đọc một cuốn sách hay.",
      topic: "entertainment",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/shu.mp3"
    },
    {
      id: 57,
      chinese: "电视",
      pinyin: "diàn shì",
      vietnamese: "tivi",
      english: "television",
      example: "晚上我看电视。",
      exampleTranslation: "Tối tôi xem tivi.",
      topic: "entertainment",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/dianshi.mp3"
    },
    {
      id: 58,
      chinese: "手机",
      pinyin: "shǒu jī",
      vietnamese: "điện thoại",
      english: "mobile phone",
      example: "我的手机坏了。",
      exampleTranslation: "Điện thoại của tôi bị hỏng.",
      topic: "technology",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/shouji.mp3"
    },
    {
      id: 59,
      chinese: "电脑",
      pinyin: "diàn nǎo",
      vietnamese: "máy tính",
      english: "computer",
      example: "我用电脑工作。",
      exampleTranslation: "Tôi dùng máy tính để làm việc.",
      topic: "technology",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/diannao.mp3"
    },
    {
      id: 60,
      chinese: "网络",
      pinyin: "wǎng luò",
      vietnamese: "mạng internet",
      english: "internet, network",
      example: "网络很重要。",
      exampleTranslation: "Mạng internet rất quan trọng.",
      topic: "technology",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/wangluo.mp3"
    },
    {
      id: 61,
      chinese: "天气",
      pinyin: "tiān qì",
      vietnamese: "thời tiết",
      english: "weather",
      example: "今天天气很好。",
      exampleTranslation: "Hôm nay thời tiết rất đẹp.",
      topic: "weather",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/tianqi.mp3"
    },
    {
      id: 62,
      chinese: "春天",
      pinyin: "chūn tiān",
      vietnamese: "mùa xuân",
      english: "spring",
      example: "春天花开了。",
      exampleTranslation: "Mùa xuân hoa nở.",
      topic: "weather",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/chuntian.mp3"
    },
    {
      id: 63,
      chinese: "夏天",
      pinyin: "xià tiān",
      vietnamese: "mùa hè",
      english: "summer",
      example: "夏天很热。",
      exampleTranslation: "Mùa hè rất nóng.",
      topic: "weather",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/xiatian.mp3"
    },
    {
      id: 64,
      chinese: "秋天",
      pinyin: "qiū tiān",
      vietnamese: "mùa thu",
      english: "autumn",
      example: "秋天叶子黄了。",
      exampleTranslation: "Mùa thu lá cây vàng.",
      topic: "weather",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/qiutian.mp3"
    },
    {
      id: 65,
      chinese: "冬天",
      pinyin: "dōng tiān",
      vietnamese: "mùa đông",
      english: "winter",
      example: "冬天下雪了。",
      exampleTranslation: "Mùa đông tuyết rơi.",
      topic: "weather",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/dongtian.mp3"
    },
    {
      id: 66,
      chinese: "健康",
      pinyin: "jiàn kāng",
      vietnamese: "sức khỏe",
      english: "health",
      example: "健康最重要。",
      exampleTranslation: "Sức khỏe là quan trọng nhất.",
      topic: "health",
      hskLevel: "HSK3",
      difficulty: "intermediate",
      audio: "/audio/jiankang.mp3"
    }
  ],  HSK4: [
    {
      id: 67,
      chinese: "经验",
      pinyin: "jīng yàn",
      vietnamese: "kinh nghiệm",
      english: "experience",
      example: "他有很多工作经验。",
      exampleTranslation: "Anh ấy có rất nhiều kinh nghiệm làm việc.",
      topic: "work",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/jingyan.mp3"
    },
    {
      id: 68,
      chinese: "机会",
      pinyin: "jī huì",
      vietnamese: "cơ hội",
      english: "opportunity",
      example: "这是一个好机会。",
      exampleTranslation: "Đây là một cơ hội tốt.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/jihui.mp3"
    },
    {
      id: 69,
      chinese: "文化",
      pinyin: "wén huà",
      vietnamese: "văn hóa",
      english: "culture",
      example: "中国文化很有趣。",
      exampleTranslation: "Văn hóa Trung Quốc rất thú vị.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/wenhua.mp3"
    },
    {
      id: 70,
      chinese: "历史",
      pinyin: "lì shǐ",
      vietnamese: "lịch sử",
      english: "history",
      example: "我喜欢学习历史。",
      exampleTranslation: "Tôi thích học lịch sử.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/lishi.mp3"
    },
    {
      id: 71,
      chinese: "社会",
      pinyin: "shè huì",
      vietnamese: "xã hội",
      english: "society",
      example: "社会在不断发展。",
      exampleTranslation: "Xã hội không ngừng phát triển.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/shehui.mp3"
    },
    {
      id: 72,
      chinese: "政府",
      pinyin: "zhèng fǔ",
      vietnamese: "chính phủ",
      english: "government",
      example: "政府制定了新政策。",
      exampleTranslation: "Chính phủ đã đưa ra chính sách mới.",
      topic: "politics",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/zhengfu.mp3"
    },
    {
      id: 73,
      chinese: "法律",
      pinyin: "fǎ lǜ",
      vietnamese: "pháp luật",
      english: "law",
      example: "我们要遵守法律。",
      exampleTranslation: "Chúng ta phải tuân thủ pháp luật.",
      topic: "politics",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/falv.mp3"
    },
    {
      id: 74,
      chinese: "科学",
      pinyin: "kē xué",
      vietnamese: "khoa học",
      english: "science",
      example: "科学技术很重要。",
      exampleTranslation: "Khoa học công nghệ rất quan trọng.",
      topic: "science",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/kexue.mp3"
    },
    {
      id: 75,
      chinese: "技术",
      pinyin: "jì shù",
      vietnamese: "công nghệ",
      english: "technology",
      example: "现代技术发展很快。",
      exampleTranslation: "Công nghệ hiện đại phát triển rất nhanh.",
      topic: "science",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/jishu.mp3"
    },
    {
      id: 76,
      chinese: "环境",
      pinyin: "huán jìng",
      vietnamese: "môi trường",
      english: "environment",
      example: "保护环境很重要。",
      exampleTranslation: "Bảo vệ môi trường rất quan trọng.",
      topic: "environment",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/huanjing.mp3"
    },
    {
      id: 77,
      chinese: "自然",
      pinyin: "zì rán",
      vietnamese: "tự nhiên",
      english: "nature",
      example: "我喜欢自然的美景。",
      exampleTranslation: "Tôi thích cảnh đẹp tự nhiên.",
      topic: "environment",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/ziran.mp3"
    },
    {
      id: 78,
      chinese: "发展",
      pinyin: "fā zhǎn",
      vietnamese: "phát triển",
      english: "development",
      example: "这个城市发展很快。",
      exampleTranslation: "Thành phố này phát triển rất nhanh.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/fazhan.mp3"
    },
    {
      id: 79,
      chinese: "改变",
      pinyin: "gǎi biàn",
      vietnamese: "thay đổi",
      english: "change",
      example: "时代在改变。",
      exampleTranslation: "Thời đại đang thay đổi.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/gaibian.mp3"
    },
    {
      id: 80,
      chinese: "进步",
      pinyin: "jìn bù",
      vietnamese: "tiến bộ",
      english: "progress",
      example: "我们取得了很大进步。",
      exampleTranslation: "Chúng ta đã đạt được tiến bộ lớn.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/jinbu.mp3"
    },
    {
      id: 81,
      chinese: "成功",
      pinyin: "chéng gōng",
      vietnamese: "thành công",
      english: "success",
      example: "努力工作会成功。",
      exampleTranslation: "Làm việc chăm chỉ sẽ thành công.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/chenggong.mp3"
    },
    {
      id: 82,
      chinese: "失败",
      pinyin: "shī bài",
      vietnamese: "thất bại",
      english: "failure",
      example: "失败是成功之母。",
      exampleTranslation: "Thất bại là mẹ của thành công.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/shibai.mp3"
    },
    {
      id: 83,
      chinese: "困难",
      pinyin: "kùn nán",
      vietnamese: "khó khăn",
      english: "difficulty",
      example: "遇到困难要坚持。",
      exampleTranslation: "Gặp khó khăn phải kiên trì.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/kunnan.mp3"
    },
    {
      id: 84,
      chinese: "解决",
      pinyin: "jiě jué",
      vietnamese: "giải quyết",
      english: "solve",
      example: "我们要解决这个问题。",
      exampleTranslation: "Chúng ta phải giải quyết vấn đề này.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/jiejue.mp3"
    },
    {
      id: 85,
      chinese: "创造",
      pinyin: "chuàng zào",
      vietnamese: "sáng tạo",
      english: "create",
      example: "我们要创造新的机会。",
      exampleTranslation: "Chúng ta phải tạo ra cơ hội mới.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/chuangzao.mp3"
    },
    {
      id: 86,
      chinese: "建设",
      pinyin: "jiàn shè",
      vietnamese: "xây dựng",
      english: "build, construct",
      example: "建设美好的未来。",
      exampleTranslation: "Xây dựng tương lai tươi đẹp.",
      topic: "abstract",
      hskLevel: "HSK4",
      difficulty: "intermediate",
      audio: "/audio/jianshe.mp3"
    }
  ],  HSK5: [
    {
      id: 87,
      chinese: "挑战",
      pinyin: "tiǎo zhàn",
      vietnamese: "thử thách",
      english: "challenge",
      example: "这是一个很大的挑战。",
      exampleTranslation: "Đây là một thử thách rất lớn.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/tiaozhan.mp3"
    },
    {
      id: 88,
      chinese: "竞争",
      pinyin: "jìng zhēng",
      vietnamese: "cạnh tranh",
      english: "competition",
      example: "市场竞争很激烈。",
      exampleTranslation: "Cạnh tranh thị trường rất khốc liệt.",
      topic: "business",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/jingzheng.mp3"
    },
    {
      id: 89,
      chinese: "合作",
      pinyin: "hé zuò",
      vietnamese: "hợp tác",
      english: "cooperation",
      example: "国际合作很重要。",
      exampleTranslation: "Hợp tác quốc tế rất quan trọng.",
      topic: "business",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/hezuo.mp3"
    },
    {
      id: 90,
      chinese: "投资",
      pinyin: "tóu zī",
      vietnamese: "đầu tư",
      english: "investment",
      example: "这是一个好的投资。",
      exampleTranslation: "Đây là một khoản đầu tư tốt.",
      topic: "business",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/touzi.mp3"
    },
    {
      id: 91,
      chinese: "经济",
      pinyin: "jīng jì",
      vietnamese: "kinh tế",
      english: "economy",
      example: "经济发展很快。",
      exampleTranslation: "Kinh tế phát triển rất nhanh.",
      topic: "business",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/jingji.mp3"
    },
    {
      id: 92,
      chinese: "市场",
      pinyin: "shì chǎng",
      vietnamese: "thị trường",
      english: "market",
      example: "这个市场很大。",
      exampleTranslation: "Thị trường này rất lớn.",
      topic: "business",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/shichang.mp3"
    },
    {
      id: 93,
      chinese: "企业",
      pinyin: "qǐ yè",
      vietnamese: "doanh nghiệp",
      english: "enterprise",
      example: "他创办了一家企业。",
      exampleTranslation: "Anh ấy đã thành lập một doanh nghiệp.",
      topic: "business",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/qiye.mp3"
    },
    {
      id: 94,
      chinese: "管理",
      pinyin: "guǎn lǐ",
      vietnamese: "quản lý",
      english: "management",
      example: "好的管理很重要。",
      exampleTranslation: "Quản lý tốt rất quan trọng.",
      topic: "business",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/guanli.mp3"
    },
    {
      id: 95,
      chinese: "责任",
      pinyin: "zé rèn",
      vietnamese: "trách nhiệm",
      english: "responsibility",
      example: "这是我的责任。",
      exampleTranslation: "Đây là trách nhiệm của tôi.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/zeren.mp3"
    },
    {
      id: 96,
      chinese: "权利",
      pinyin: "quán lì",
      vietnamese: "quyền lợi",
      english: "rights",
      example: "每个人都有自己的权利。",
      exampleTranslation: "Mỗi người đều có quyền lợi của mình.",
      topic: "politics",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/quanli.mp3"
    },
    {
      id: 97,
      chinese: "义务",
      pinyin: "yì wù",
      vietnamese: "nghĩa vụ",
      english: "obligation",
      example: "这是公民的义务。",
      exampleTranslation: "Đây là nghĩa vụ của công dân.",
      topic: "politics",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/yiwu.mp3"
    },
    {
      id: 98,
      chinese: "自由",
      pinyin: "zì yóu",
      vietnamese: "tự do",
      english: "freedom",
      example: "自由很珍贵。",
      exampleTranslation: "Tự do rất quý giá.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/ziyou.mp3"
    },
    {
      id: 99,
      chinese: "平等",
      pinyin: "píng děng",
      vietnamese: "bình đẳng",
      english: "equality",
      example: "人人生而平等。",
      exampleTranslation: "Con người sinh ra đều bình đẳng.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/pingdeng.mp3"
    },
    {
      id: 100,
      chinese: "和谐",
      pinyin: "hé xié",
      vietnamese: "hòa hợp",
      english: "harmony",
      example: "社会需要和谐。",
      exampleTranslation: "Xã hội cần sự hòa hợp.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/hexie.mp3"
    },
    {
      id: 101,
      chinese: "创新",
      pinyin: "chuàng xīn",
      vietnamese: "đổi mới",
      english: "innovation",
      example: "创新推动发展。",
      exampleTranslation: "Đổi mới thúc đẩy phát triển.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/chuangxin.mp3"
    },
    {
      id: 102,
      chinese: "效率",
      pinyin: "xiào lǜ",
      vietnamese: "hiệu quả",
      english: "efficiency",
      example: "提高工作效率。",
      exampleTranslation: "Nâng cao hiệu quả công việc.",
      topic: "work",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/xiaolv.mp3"
    },
    {
      id: 103,
      chinese: "质量",
      pinyin: "zhì liàng",
      vietnamese: "chất lượng",
      english: "quality",
      example: "质量比数量重要。",
      exampleTranslation: "Chất lượng quan trọng hơn số lượng.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/zhiliang.mp3"
    },
    {
      id: 104,
      chinese: "标准",
      pinyin: "biāo zhǔn",
      vietnamese: "tiêu chuẩn",
      english: "standard",
      example: "这是国际标准。",
      exampleTranslation: "Đây là tiêu chuẩn quốc tế.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/biaozhun.mp3"
    },
    {
      id: 105,
      chinese: "理想",
      pinyin: "lǐ xiǎng",
      vietnamese: "lý tưởng",
      english: "ideal",
      example: "每个人都有理想。",
      exampleTranslation: "Mỗi người đều có lý tưởng.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/lixiang.mp3"
    },
    {
      id: 106,
      chinese: "现实",
      pinyin: "xiàn shí",
      vietnamese: "thực tế",
      english: "reality",
      example: "理想和现实有差距。",
      exampleTranslation: "Lý tưởng và thực tế có khoảng cách.",
      topic: "abstract",
      hskLevel: "HSK5",
      difficulty: "advanced",
      audio: "/audio/xianshi.mp3"
    }
  ]
};

// Flatten all HSK data for backward compatibility
export const vocabularyData = Object.values(hskVocabularyData).flat();

// HSK Levels configuration
export const hskLevels = [
  { id: "HSK1", name: "HSK 1", description: "Cơ bản nhất", color: "green", wordCount: 22 },
  { id: "HSK2", name: "HSK 2", description: "Cơ bản", color: "blue", wordCount: 22 },
  { id: "HSK3", name: "HSK 3", description: "Trung cấp", color: "orange", wordCount: 22 },
  { id: "HSK4", name: "HSK 4", description: "Trung cấp cao", color: "purple", wordCount: 20 },
  { id: "HSK5", name: "HSK 5", description: "Nâng cao", color: "red", wordCount: 20 }
];

// Topics data updated with HSK levels
export const topicsData = [
  {
    id: "greetings",
    name: "Chào hỏi",
    description: "Các câu chào hỏi cơ bản",
    icon: "👋",
    wordCount: 2,
    color: "blue",
    hskLevels: ["HSK1"]
  },
  {
    id: "pronouns",
    name: "Đại từ",
    description: "Các đại từ cơ bản",
    icon: "👤",
    wordCount: 3,
    color: "yellow",
    hskLevels: ["HSK1"]
  },
  {
    id: "grammar",
    name: "Ngữ pháp",
    description: "Từ ngữ pháp cơ bản",
    icon: "📝",
    wordCount: 2,
    color: "gray",
    hskLevels: ["HSK1"]
  },
  {
    id: "questions",
    name: "Câu hỏi",
    description: "Từ để hỏi",
    icon: "❓",
    wordCount: 2,
    color: "indigo",
    hskLevels: ["HSK1"]
  },
  {
    id: "demonstratives",
    name: "Từ chỉ định",
    description: "Này, kia, đó",
    icon: "👆",
    wordCount: 2,
    color: "pink",
    hskLevels: ["HSK1"]
  },
  {
    id: "food",
    name: "Thức ăn",
    description: "Từ vựng về đồ ăn uống",
    icon: "🍽️",
    wordCount: 4,
    color: "orange",
    hskLevels: ["HSK1"]
  },
  {
    id: "numbers",
    name: "Số đếm",
    description: "Các số cơ bản",
    icon: "🔢",
    wordCount: 3,
    color: "green",
    hskLevels: ["HSK1"]
  },
  {
    id: "countries",
    name: "Quốc gia",
    description: "Tên các nước",
    icon: "🌍",
    wordCount: 1,
    color: "red",
    hskLevels: ["HSK1"]
  },
  {
    id: "people",
    name: "Con người",
    description: "Từ vựng về con người",
    icon: "👥",
    wordCount: 2,
    color: "purple",
    hskLevels: ["HSK1"]
  },
  {
    id: "family",
    name: "Gia đình",
    description: "Từ vựng về thành viên gia đình",
    icon: "👨‍👩‍👧‍👦",
    wordCount: 3,
    color: "green",
    hskLevels: ["HSK2"]
  },
  {
    id: "education",
    name: "Giáo dục",
    description: "Từ vựng về học tập",
    icon: "📚",
    wordCount: 4,
    color: "blue",
    hskLevels: ["HSK2"]
  },
  {
    id: "work",
    name: "Công việc",
    description: "Từ vựng về nghề nghiệp",
    icon: "💼",
    wordCount: 3,
    color: "purple",
    hskLevels: ["HSK2", "HSK4", "HSK5"]
  },
  {
    id: "time",
    name: "Thời gian",
    description: "Từ vựng về thời gian",
    icon: "⏰",
    wordCount: 6,
    color: "orange",
    hskLevels: ["HSK2"]
  },
  {
    id: "shopping",
    name: "Mua sắm",
    description: "Từ vựng về mua bán",
    icon: "🛒",
    wordCount: 5,
    color: "yellow",
    hskLevels: ["HSK2"]
  },
  {
    id: "home",
    name: "Nhà ở",
    description: "Từ vựng về nhà cửa",
    icon: "🏠",
    wordCount: 1,
    color: "brown",
    hskLevels: ["HSK2"]
  },
  {
    id: "travel",
    name: "Du lịch",
    description: "Từ vựng liên quan đến du lịch",
    icon: "✈️",
    wordCount: 5,
    color: "cyan",
    hskLevels: ["HSK3"]
  },
  {
    id: "sports",
    name: "Thể thao",
    description: "Các môn thể thao",
    icon: "⚽",
    wordCount: 4,
    color: "green",
    hskLevels: ["HSK3"]
  },
  {
    id: "entertainment",
    name: "Giải trí",
    description: "Hoạt động giải trí",
    icon: "🎭",
    wordCount: 4,
    color: "purple",
    hskLevels: ["HSK3"]
  },
  {
    id: "technology",
    name: "Công nghệ",
    description: "Từ vựng về công nghệ",
    icon: "💻",
    wordCount: 3,
    color: "blue",
    hskLevels: ["HSK3", "HSK4"]
  },
  {
    id: "weather",
    name: "Thời tiết",
    description: "Từ vựng về thời tiết, mùa",
    icon: "🌤️",
    wordCount: 6,
    color: "lightblue",
    hskLevels: ["HSK3"]
  },
  {
    id: "health",
    name: "Sức khỏe",
    description: "Từ vựng về sức khỏe",
    icon: "🏥",
    wordCount: 1,
    color: "red",
    hskLevels: ["HSK3"]
  },
  {
    id: "abstract",
    name: "Trừu tượng",
    description: "Các khái niệm trừu tượng",
    icon: "💭",
    wordCount: 15,
    color: "gray",
    hskLevels: ["HSK4", "HSK5"]
  },
  {
    id: "politics",
    name: "Chính trị",
    description: "Từ vựng về chính trị, pháp luật",
    icon: "🏛️",
    wordCount: 4,
    color: "darkblue",
    hskLevels: ["HSK4", "HSK5"]
  },
  {
    id: "science",
    name: "Khoa học",
    description: "Từ vựng về khoa học công nghệ",
    icon: "🔬",
    wordCount: 2,
    color: "green",
    hskLevels: ["HSK4"]
  },
  {
    id: "environment",
    name: "Môi trường",
    description: "Từ vựng về môi trường, tự nhiên",
    icon: "🌱",
    wordCount: 2,
    color: "green",
    hskLevels: ["HSK4"]
  },
  {
    id: "business",
    name: "Kinh doanh",
    description: "Từ vựng về kinh tế, kinh doanh",
    icon: "💰",
    wordCount: 6,
    color: "gold",
    hskLevels: ["HSK5"]
  }
];

// Get vocabulary by HSK level
export function getVocabularyByHSK(hskLevel) {
  return hskVocabularyData[hskLevel] || [];
}

// Get vocabulary by topic
export function getVocabularyByTopic(topicId) {
  return vocabularyData.filter(word => word.topic === topicId);
}

// Get vocabulary by topic and HSK level
export function getVocabularyByTopicAndHSK(topicId, hskLevel) {
  return vocabularyData.filter(word => word.topic === topicId && word.hskLevel === hskLevel);
}

// Get random vocabulary for quiz
export function getRandomVocabulary(count = 10, hskLevel = null) {
  let data = hskLevel ? getVocabularyByHSK(hskLevel) : vocabularyData;
  const shuffled = [...data].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

// Get topics by HSK level
export function getTopicsByHSK(hskLevel) {
  return topicsData.filter(topic => topic.hskLevels.includes(hskLevel));
}

// Get words by topic
export function getWordsByTopic(topicId) {
  return vocabularyData.filter(word => word.topic === topicId);
}
