// HSK 1 Vocabulary
export default [
  {
    id: "hsk1_001",
    chinese: "你好",
    pinyin: "nǐ hǎo",
    vietnamese: "xin chào",
    english: "hello",
    example: "你好，很高兴见到你。",
    exampleTranslation: "Xin chào, rất vui được gặp bạn.",
    topic: "greetings",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/nihao.mp3"
  },
  {
    id: "hsk1_002",
    chinese: "谢谢",
    pinyin: "xiè xiè",
    vietnamese: "cảm ơn",
    english: "thank you",
    example: "谢谢你的帮助。",
    exampleTranslation: "Cảm ơn sự giúp đỡ của bạn.",
    topic: "greetings",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/xiexie.mp3"
  },
  {
    id: "hsk1_003",
    chinese: "我",
    pinyin: "wǒ",
    vietnamese: "tôi",
    english: "I, me",
    example: "我是学生。",
    exampleTranslation: "Tôi là học sinh.",
    topic: "pronouns",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/wo.mp3"
  },
  {
    id: "hsk1_004",
    chinese: "的",
    pinyin: "de",
    vietnamese: "của",
    english: "of, possessive particle",
    example: "这是我的书。",
    exampleTranslation: "Đây là quyển sách của tôi.",
    topic: "grammar",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/de.mp3"
  },
  {
    id: "hsk1_005",
    chinese: "你",
    pinyin: "nǐ",
    vietnamese: "bạn",
    english: "you",
    example: "你是老师吗？",
    exampleTranslation: "Bạn có phải là giáo viên không?",
    topic: "pronouns",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ni.mp3"
  },
  {
    id: "hsk1_006",
    chinese: "他",
    pinyin: "tā",
    vietnamese: "anh ấy",
    english: "he, him",
    example: "他是我的朋友。",
    exampleTranslation: "Anh ấy là bạn của tôi.",
    topic: "pronouns",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ta.mp3"
  },
  {
    id: "hsk1_007",
    chinese: "是",
    pinyin: "shì",
    vietnamese: "là",
    english: "to be",
    example: "我是中国人。",
    exampleTranslation: "Tôi là người Trung Quốc.",
    topic: "grammar",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/shi.mp3"
  },
  {
    id: "hsk1_008",
    chinese: "不",
    pinyin: "bù",
    vietnamese: "không",
    english: "no, not",
    example: "我不是老师。",
    exampleTranslation: "Tôi không phải là giáo viên.",
    topic: "grammar",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/bu.mp3"
  },
  {
    id: "hsk1_009",
    chinese: "这",
    pinyin: "zhè",
    vietnamese: "này",
    english: "this",
    example: "这是什么？",
    exampleTranslation: "Cái này là gì?",
    topic: "demonstratives",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/zhe.mp3"
  },
  {
    id: "hsk1_010",
    chinese: "那",
    pinyin: "nà",
    vietnamese: "kia",
    english: "that",
    example: "那是我的车。",
    exampleTranslation: "Cái kia là xe của tôi.",
    topic: "demonstratives",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/na.mp3"
  },
  {
    id: "hsk1_011",
    chinese: "什么",
    pinyin: "shén me",
    vietnamese: "gì, cái gì",
    english: "what",
    example: "你叫什么名字？",
    exampleTranslation: "Bạn tên là gì?",
    topic: "questions",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/shenme.mp3"
  },
  {
    id: "hsk1_012",
    chinese: "哪",
    pinyin: "nǎ",
    vietnamese: "nào",
    english: "which",
    example: "你是哪国人？",
    exampleTranslation: "Bạn là người nước nào?",
    topic: "questions",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/na.mp3"
  },
  {
    id: "hsk1_013",
    chinese: "水",
    pinyin: "shuǐ",
    vietnamese: "nước",
    english: "water",
    example: "我想喝水。",
    exampleTranslation: "Tôi muốn uống nước.",
    topic: "food",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/shui.mp3"
  },
  {
    id: "hsk1_014",
    chinese: "茶",
    pinyin: "chá",
    vietnamese: "trà",
    english: "tea",
    example: "我喜欢喝茶。",
    exampleTranslation: "Tôi thích uống trà.",
    topic: "food",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/cha.mp3"
  },
  {
    id: "hsk1_015",
    chinese: "吃",
    pinyin: "chī",
    vietnamese: "ăn",
    english: "to eat",
    example: "我们一起吃饭吧。",
    exampleTranslation: "Chúng ta cùng ăn cơm nhé.",
    topic: "food",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/chi.mp3"
  },
  {
    id: "hsk1_016",
    chinese: "喝",
    pinyin: "hē",
    vietnamese: "uống",
    english: "to drink",
    example: "你喝什么？",
    exampleTranslation: "Bạn uống gì?",
    topic: "food",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/he.mp3"
  },
  {
    id: "hsk1_017",
    chinese: "一",
    pinyin: "yī",
    vietnamese: "một",
    english: "one",
    example: "一个苹果。",
    exampleTranslation: "Một quả táo.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/yi.mp3"
  },
  {
    id: "hsk1_018",
    chinese: "二",
    pinyin: "èr",
    vietnamese: "hai",
    english: "two",
    example: "二十块钱。",
    exampleTranslation: "Hai mười đồng.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/er.mp3"
  },
  {
    id: "hsk1_019",
    chinese: "三",
    pinyin: "sān",
    vietnamese: "ba",
    english: "three",
    example: "三点钟。",
    exampleTranslation: "Ba giờ.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/san.mp3"
  },
  {
    id: "hsk1_020",
    chinese: "中国",
    pinyin: "zhōng guó",
    vietnamese: "Trung Quốc",
    english: "China",
    example: "我来自中国。",
    exampleTranslation: "Tôi đến từ Trung Quốc.",
    topic: "countries",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/zhongguo.mp3"
  },
  {
    id: "hsk1_021",
    chinese: "人",
    pinyin: "rén",
    vietnamese: "người",
    english: "person, people",
    example: "他是好人。",
    exampleTranslation: "Anh ấy là người tốt.",
    topic: "people",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ren.mp3"
  },
  {
    id: "hsk1_022",
    chinese: "朋友",
    pinyin: "péng yǒu",
    vietnamese: "bạn bè",
    english: "friend",
    example: "我们是好朋友。",
    exampleTranslation: "Chúng tôi là bạn tốt.",
    topic: "people",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/pengyou.mp3"
  },
  {
    id: "hsk1_023",
    chinese: "她",
    pinyin: "tā",
    vietnamese: "cô ấy",
    english: "she, her",
    example: "她是我的妹妹。",
    exampleTranslation: "Cô ấy là em gái tôi.",
    topic: "pronouns",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ta_female.mp3"
  },
  {
    id: "hsk1_024",
    chinese: "它",
    pinyin: "tā",
    vietnamese: "nó",
    english: "it",
    example: "它是我的猫。",
    exampleTranslation: "Nó là con mèo của tôi.",
    topic: "pronouns",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ta_it.mp3"
  },
  {
    id: "hsk1_025",
    chinese: "我们",
    pinyin: "wǒ men",
    vietnamese: "chúng tôi",
    english: "we, us",
    example: "我们是学生。",
    exampleTranslation: "Chúng tôi là học sinh.",
    topic: "pronouns",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/women.mp3"
  },
  {
    id: "hsk1_026",
    chinese: "你们",
    pinyin: "nǐ men",
    vietnamese: "các bạn",
    english: "you (plural)",
    example: "你们好吗？",
    exampleTranslation: "Các bạn có khỏe không?",
    topic: "pronouns",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/nimen.mp3"
  },
  {
    id: "hsk1_027",
    chinese: "他们",
    pinyin: "tā men",
    vietnamese: "họ",
    english: "they, them",
    example: "他们是老师。",
    exampleTranslation: "Họ là giáo viên.",
    topic: "pronouns",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/tamen.mp3"
  },
  {
    id: "hsk1_028",
    chinese: "四",
    pinyin: "sì",
    vietnamese: "bốn",
    english: "four",
    example: "四个人。",
    exampleTranslation: "Bốn người.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/si.mp3"
  },
  {
    id: "hsk1_029",
    chinese: "五",
    pinyin: "wǔ",
    vietnamese: "năm",
    english: "five",
    example: "五本书。",
    exampleTranslation: "Năm quyển sách.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/wu.mp3"
  },
  {
    id: "hsk1_030",
    chinese: "六",
    pinyin: "liù",
    vietnamese: "sáu",
    english: "six",
    example: "六点钟。",
    exampleTranslation: "Sáu giờ.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/liu.mp3"
  },
  {
    id: "hsk1_031",
    chinese: "七",
    pinyin: "qī",
    vietnamese: "bảy",
    english: "seven",
    example: "七天。",
    exampleTranslation: "Bảy ngày.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/qi.mp3"
  },
  {
    id: "hsk1_032",
    chinese: "八",
    pinyin: "bā",
    vietnamese: "tám",
    english: "eight",
    example: "八个月。",
    exampleTranslation: "Tám tháng.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ba.mp3"
  },
  {
    id: "hsk1_033",
    chinese: "九",
    pinyin: "jiǔ",
    vietnamese: "chín",
    english: "nine",
    example: "九岁。",
    exampleTranslation: "Chín tuổi.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/jiu.mp3"
  },
  {
    id: "hsk1_034",
    chinese: "十",
    pinyin: "shí",
    vietnamese: "mười",
    english: "ten",
    example: "十个苹果。",
    exampleTranslation: "Mười quả táo.",
    topic: "numbers",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/shi.mp3"
  },
  {
    id: "hsk1_035",
    chinese: "有",
    pinyin: "yǒu",
    vietnamese: "có",
    english: "to have",
    example: "我有一本书。",
    exampleTranslation: "Tôi có một quyển sách.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/you.mp3"
  },
  {
    id: "hsk1_036",
    chinese: "在",
    pinyin: "zài",
    vietnamese: "ở",
    english: "at, in, on",
    example: "我在家。",
    exampleTranslation: "Tôi ở nhà.",
    topic: "prepositions",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/zai.mp3"
  },
  {
    id: "hsk1_037",
    chinese: "来",
    pinyin: "lái",
    vietnamese: "đến",
    english: "to come",
    example: "请来我家。",
    exampleTranslation: "Hãy đến nhà tôi.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/lai.mp3"
  },
  {
    id: "hsk1_038",
    chinese: "去",
    pinyin: "qù",
    vietnamese: "đi",
    english: "to go",
    example: "我去学校。",
    exampleTranslation: "Tôi đi học.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/qu.mp3"
  },
  {
    id: "hsk1_039",
    chinese: "看",
    pinyin: "kàn",
    vietnamese: "xem, nhìn",
    english: "to see, to look",
    example: "我看电视。",
    exampleTranslation: "Tôi xem tivi.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/kan.mp3"
  },
  {
    id: "hsk1_040",
    chinese: "听",
    pinyin: "tīng",
    vietnamese: "nghe",
    english: "to listen",
    example: "我听音乐。",
    exampleTranslation: "Tôi nghe nhạc.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ting.mp3"
  },
  {
    id: "hsk1_041",
    chinese: "说",
    pinyin: "shuō",
    vietnamese: "nói",
    english: "to speak, to say",
    example: "我说中文。",
    exampleTranslation: "Tôi nói tiếng Trung.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/shuo.mp3"
  },
  {
    id: "hsk1_042",
    chinese: "读",
    pinyin: "dú",
    vietnamese: "đọc",
    english: "to read",
    example: "我读书。",
    exampleTranslation: "Tôi đọc sách.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/du.mp3"
  },
  {
    id: "hsk1_043",
    chinese: "写",
    pinyin: "xiě",
    vietnamese: "viết",
    english: "to write",
    example: "我写字。",
    exampleTranslation: "Tôi viết chữ.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/xie.mp3"
  },
  {
    id: "hsk1_044",
    chinese: "叫",
    pinyin: "jiào",
    vietnamese: "gọi",
    english: "to be called",
    example: "我叫李明。",
    exampleTranslation: "Tôi tên là Lý Minh.",
    topic: "verbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/jiao.mp3"
  },
  {
    id: "hsk1_045",
    chinese: "名字",
    pinyin: "míng zi",
    vietnamese: "tên",
    english: "name",
    example: "你的名字是什么？",
    exampleTranslation: "Tên bạn là gì?",
    topic: "basic_info",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/mingzi.mp3"
  },
  {
    id: "hsk1_046",
    chinese: "家",
    pinyin: "jiā",
    vietnamese: "nhà",
    english: "home, family",
    example: "我回家。",
    exampleTranslation: "Tôi về nhà.",
    topic: "places",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/jia.mp3"
  },
  {
    id: "hsk1_047",
    chinese: "学校",
    pinyin: "xué xiào",
    vietnamese: "trường học",
    english: "school",
    example: "我在学校。",
    exampleTranslation: "Tôi ở trường.",
    topic: "places",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/xuexiao.mp3"
  },
  {
    id: "hsk1_048",
    chinese: "老师",
    pinyin: "lǎo shī",
    vietnamese: "giáo viên",
    english: "teacher",
    example: "她是老师。",
    exampleTranslation: "Cô ấy là giáo viên.",
    topic: "people",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/laoshi.mp3"
  },
  {
    id: "hsk1_049",
    chinese: "学生",
    pinyin: "xué shēng",
    vietnamese: "học sinh",
    english: "student",
    example: "我是学生。",
    exampleTranslation: "Tôi là học sinh.",
    topic: "people",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/xuesheng.mp3"
  },
  {
    id: "hsk1_050",
    chinese: "医生",
    pinyin: "yī shēng",
    vietnamese: "bác sĩ",
    english: "doctor",
    example: "他是医生。",
    exampleTranslation: "Anh ấy là bác sĩ.",
    topic: "people",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/yisheng.mp3"
  },
  {
    id: "hsk1_051",
    chinese: "大",
    pinyin: "dà",
    vietnamese: "lớn",
    english: "big, large",
    example: "大房子。",
    exampleTranslation: "Ngôi nhà lớn.",
    topic: "adjectives",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/da.mp3"
  },
  {
    id: "hsk1_052",
    chinese: "小",
    pinyin: "xiǎo",
    vietnamese: "nhỏ",
    english: "small, little",
    example: "小猫。",
    exampleTranslation: "Con mèo nhỏ.",
    topic: "adjectives",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/xiao.mp3"
  },
  {
    id: "hsk1_053",
    chinese: "多",
    pinyin: "duō",
    vietnamese: "nhiều",
    english: "many, much",
    example: "很多人。",
    exampleTranslation: "Rất nhiều người.",
    topic: "adjectives",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/duo.mp3"
  },
  {
    id: "hsk1_054",
    chinese: "少",
    pinyin: "shǎo",
    vietnamese: "ít",
    english: "few, little",
    example: "少钱。",
    exampleTranslation: "Ít tiền.",
    topic: "adjectives",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/shao.mp3"
  },
  {
    id: "hsk1_055",
    chinese: "好",
    pinyin: "hǎo",
    vietnamese: "tốt",
    english: "good, well",
    example: "很好。",
    exampleTranslation: "Rất tốt.",
    topic: "adjectives",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/hao.mp3"
  },
  {
    id: "hsk1_056",
    chinese: "很",
    pinyin: "hěn",
    vietnamese: "rất",
    english: "very",
    example: "很高兴。",
    exampleTranslation: "Rất vui.",
    topic: "adverbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/hen.mp3"
  },
  {
    id: "hsk1_057",
    chinese: "都",
    pinyin: "dōu",
    vietnamese: "đều",
    english: "all, both",
    example: "我们都是学生。",
    exampleTranslation: "Chúng tôi đều là học sinh.",
    topic: "adverbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/dou.mp3"
  },
  {
    id: "hsk1_058",
    chinese: "也",
    pinyin: "yě",
    vietnamese: "cũng",
    english: "also, too",
    example: "我也是学生。",
    exampleTranslation: "Tôi cũng là học sinh.",
    topic: "adverbs",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ye.mp3"
  },
  {
    id: "hsk1_059",
    chinese: "吗",
    pinyin: "ma",
    vietnamese: "không",
    english: "question particle",
    example: "你好吗？",
    exampleTranslation: "Bạn có khỏe không?",
    topic: "grammar",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ma.mp3"
  },
  {
    id: "hsk1_060",
    chinese: "呢",
    pinyin: "ne",
    vietnamese: "còn... thì sao",
    english: "question particle",
    example: "你呢？",
    exampleTranslation: "Còn bạn thì sao?",
    topic: "grammar",
    hskLevel: "HSK1",
    difficulty: "beginner",
    audio: "/audio/ne.mp3"
  }
];
