// HSK 2 Vocabulary
export default [
  {
    id: "hsk2_001",
    chinese: "家庭",
    pinyin: "jiā tíng",
    vietnamese: "gia đình",
    english: "family",
    example: "我有一个幸福的家庭。",
    exampleTranslation: "Tôi có một gia đình hạnh phúc.",
    topic: "family",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/jiating.mp3"
  },
  {
    id: "hsk2_002",
    chinese: "妈妈",
    pinyin: "mā ma",
    vietnamese: "mẹ",
    english: "mother",
    example: "我的妈妈很漂亮。",
    exampleTranslation: "Mẹ tôi rất xinh đẹp.",
    topic: "family",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/mama.mp3"
  },
  {
    id: "hsk2_003",
    chinese: "爸爸",
    pinyin: "bà ba",
    vietnamese: "bố",
    english: "father",
    example: "我爸爸是医生。",
    exampleTranslation: "Bố tôi là bác sĩ.",
    topic: "family",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/baba.mp3"
  },
  {
    id: "hsk2_004",
    chinese: "工作",
    pinyin: "gōng zuò",
    vietnamese: "công việc",
    english: "work, job",
    example: "我的工作很忙。",
    exampleTranslation: "Công việc của tôi rất bận.",
    topic: "work",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/gongzuo.mp3"
  },
  {
    id: "hsk2_005",
    chinese: "时间",
    pinyin: "shí jiān",
    vietnamese: "thời gian",
    english: "time",
    example: "时间过得很快。",
    exampleTranslation: "Thời gian trôi qua rất nhanh.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/shijian.mp3"
  },
  {
    id: "hsk2_006",
    chinese: "今天",
    pinyin: "jīn tiān",
    vietnamese: "hôm nay",
    english: "today",
    example: "今天天气很好。",
    exampleTranslation: "Hôm nay thời tiết rất đẹp.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/jintian.mp3"
  },
  {
    id: "hsk2_007",
    chinese: "明天",
    pinyin: "míng tiān",
    vietnamese: "ngày mai",
    english: "tomorrow",
    example: "明天我要去北京。",
    exampleTranslation: "Ngày mai tôi sẽ đi Bắc Kinh.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/mingtian.mp3"
  },
  {
    id: "hsk2_008",
    chinese: "昨天",
    pinyin: "zuó tiān",
    vietnamese: "hôm qua",
    english: "yesterday",
    example: "昨天我看了电影。",
    exampleTranslation: "Hôm qua tôi đã xem phim.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/zuotian.mp3"
  },
  {
    id: "hsk2_009",
    chinese: "年",
    pinyin: "nián",
    vietnamese: "năm",
    english: "year",
    example: "我二十岁了。",
    exampleTranslation: "Tôi hai mười tuổi rồi.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/nian.mp3"
  },
  {
    id: "hsk2_010",
    chinese: "月",
    pinyin: "yuè",
    vietnamese: "tháng",
    english: "month",
    example: "这个月很忙。",
    exampleTranslation: "Tháng này rất bận.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/yue.mp3"
  },
  {
    id: "hsk2_011",
    chinese: "天",
    pinyin: "tiān",
    vietnamese: "ngày",
    english: "day",
    example: "一天有二十四小时。",
    exampleTranslation: "Một ngày có hai mười bốn giờ.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/tian.mp3"
  },
  {
    id: "hsk2_012",
    chinese: "钱",
    pinyin: "qián",
    vietnamese: "tiền",
    english: "money",
    example: "这个多少钱？",
    exampleTranslation: "Cái này bao nhiêu tiền?",
    topic: "shopping",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/qian.mp3"
  },
  {
    id: "hsk2_013",
    chinese: "买",
    pinyin: "mǎi",
    vietnamese: "mua",
    english: "to buy",
    example: "我想买这个。",
    exampleTranslation: "Tôi muốn mua cái này.",
    topic: "shopping",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/mai.mp3"
  },
  {
    id: "hsk2_014",
    chinese: "卖",
    pinyin: "mài",
    vietnamese: "bán",
    english: "to sell",
    example: "他卖水果。",
    exampleTranslation: "Anh ấy bán trái cây.",
    topic: "shopping",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/mai2.mp3"
  },
  {
    id: "hsk2_015",
    chinese: "商店",
    pinyin: "shāng diàn",
    vietnamese: "cửa hàng",
    english: "shop, store",
    example: "这个商店很大。",
    exampleTranslation: "Cửa hàng này rất lớn.",
    topic: "shopping",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/shangdian.mp3"
  },
  {
    id: "hsk2_016",
    chinese: "衣服",
    pinyin: "yī fú",
    vietnamese: "quần áo",
    english: "clothes",
    example: "我要买新衣服。",
    exampleTranslation: "Tôi muốn mua quần áo mới.",
    topic: "shopping",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/yifu.mp3"
  },
  {
    id: "hsk2_017",
    chinese: "房子",
    pinyin: "fáng zi",
    vietnamese: "nhà",
    english: "house",
    example: "我们的房子很漂亮。",
    exampleTranslation: "Ngôi nhà của chúng tôi rất đẹp.",
    topic: "home",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/fangzi.mp3"
  },
  {
    id: "hsk2_018",
    chinese: "学习",
    pinyin: "xué xí",
    vietnamese: "học tập",
    english: "to study",
    example: "我每天学习中文。",
    exampleTranslation: "Tôi học tiếng Trung mỗi ngày.",
    topic: "education",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/xuexi.mp3"
  },
  {
    id: "hsk2_019",
    chinese: "上课",
    pinyin: "shàng kè",
    vietnamese: "lên lớp",
    english: "to attend class",
    example: "我们八点上课。",
    exampleTranslation: "Chúng tôi lên lớp lúc tám giờ.",
    topic: "education",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/shangke.mp3"
  },
  {
    id: "hsk2_020",
    chinese: "下课",
    pinyin: "xià kè",
    vietnamese: "tan học",
    english: "class is over",
    example: "下课了。",
    exampleTranslation: "Tan học rồi.",
    topic: "education",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/xiake.mp3"
  },
  {
    id: "hsk2_021",
    chinese: "早上",
    pinyin: "zǎo shang",
    vietnamese: "buổi sáng",
    english: "morning",
    example: "早上好。",
    exampleTranslation: "Chào buổi sáng.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/zaoshang.mp3"
  },
  {
    id: "hsk2_022",
    chinese: "中午",
    pinyin: "zhōng wǔ",
    vietnamese: "buổi trưa",
    english: "noon",
    example: "中午吃饭。",
    exampleTranslation: "Ăn cơm trưa.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/zhongwu.mp3"
  },
  {
    id: "hsk2_023",
    chinese: "晚上",
    pinyin: "wǎn shang",
    vietnamese: "buổi tối",
    english: "evening",
    example: "晚上好。",
    exampleTranslation: "Chào buổi tối.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/wanshang.mp3"
  },
  {
    id: "hsk2_024",
    chinese: "现在",
    pinyin: "xiàn zài",
    vietnamese: "bây giờ",
    english: "now",
    example: "现在几点？",
    exampleTranslation: "Bây giờ mấy giờ?",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/xianzai.mp3"
  },
  {
    id: "hsk2_025",
    chinese: "点",
    pinyin: "diǎn",
    vietnamese: "giờ",
    english: "o'clock",
    example: "三点。",
    exampleTranslation: "Ba giờ.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/dian.mp3"
  },
  {
    id: "hsk2_026",
    chinese: "分",
    pinyin: "fēn",
    vietnamese: "phút",
    english: "minute",
    example: "十分钟。",
    exampleTranslation: "Mười phút.",
    topic: "time",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/fen.mp3"
  },
  {
    id: "hsk2_027",
    chinese: "上",
    pinyin: "shàng",
    vietnamese: "lên, trên",
    english: "up, on",
    example: "上楼。",
    exampleTranslation: "Lên lầu.",
    topic: "directions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/shang.mp3"
  },
  {
    id: "hsk2_028",
    chinese: "下",
    pinyin: "xià",
    vietnamese: "xuống, dưới",
    english: "down, under",
    example: "下楼。",
    exampleTranslation: "Xuống lầu.",
    topic: "directions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/xia.mp3"
  },
  {
    id: "hsk2_029",
    chinese: "左",
    pinyin: "zuǒ",
    vietnamese: "trái",
    english: "left",
    example: "向左转。",
    exampleTranslation: "Rẽ trái.",
    topic: "directions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/zuo.mp3"
  },
  {
    id: "hsk2_030",
    chinese: "右",
    pinyin: "yòu",
    vietnamese: "phải",
    english: "right",
    example: "向右转。",
    exampleTranslation: "Rẽ phải.",
    topic: "directions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/you_direction.mp3"
  },
  {
    id: "hsk2_031",
    chinese: "前",
    pinyin: "qián",
    vietnamese: "trước",
    english: "front",
    example: "前面。",
    exampleTranslation: "Phía trước.",
    topic: "directions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/qian.mp3"
  },
  {
    id: "hsk2_032",
    chinese: "后",
    pinyin: "hòu",
    vietnamese: "sau",
    english: "back, behind",
    example: "后面。",
    exampleTranslation: "Phía sau.",
    topic: "directions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/hou.mp3"
  },
  {
    id: "hsk2_033",
    chinese: "里",
    pinyin: "lǐ",
    vietnamese: "trong",
    english: "inside",
    example: "房间里。",
    exampleTranslation: "Trong phòng.",
    topic: "prepositions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/li.mp3"
  },
  {
    id: "hsk2_034",
    chinese: "外",
    pinyin: "wài",
    vietnamese: "ngoài",
    english: "outside",
    example: "外面下雨。",
    exampleTranslation: "Ngoài trời mưa.",
    topic: "prepositions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/wai.mp3"
  },
  {
    id: "hsk2_035",
    chinese: "上面",
    pinyin: "shàng miàn",
    vietnamese: "phía trên",
    english: "above, on top",
    example: "桌子上面。",
    exampleTranslation: "Trên bàn.",
    topic: "prepositions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/shangmian.mp3"
  },
  {
    id: "hsk2_036",
    chinese: "下面",
    pinyin: "xià miàn",
    vietnamese: "phía dưới",
    english: "below, under",
    example: "桌子下面。",
    exampleTranslation: "Dưới bàn.",
    topic: "prepositions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/xiamian.mp3"
  },
  {
    id: "hsk2_037",
    chinese: "旁边",
    pinyin: "páng biān",
    vietnamese: "bên cạnh",
    english: "beside, next to",
    example: "学校旁边。",
    exampleTranslation: "Bên cạnh trường học.",
    topic: "prepositions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/pangbian.mp3"
  },
  {
    id: "hsk2_038",
    chinese: "对面",
    pinyin: "duì miàn",
    vietnamese: "đối diện",
    english: "opposite",
    example: "银行对面。",
    exampleTranslation: "Đối diện ngân hàng.",
    topic: "prepositions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/duimian.mp3"
  },
  {
    id: "hsk2_039",
    chinese: "远",
    pinyin: "yuǎn",
    vietnamese: "xa",
    english: "far",
    example: "很远。",
    exampleTranslation: "Rất xa.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/yuan.mp3"
  },
  {
    id: "hsk2_040",
    chinese: "近",
    pinyin: "jìn",
    vietnamese: "gần",
    english: "near, close",
    example: "很近。",
    exampleTranslation: "Rất gần.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/jin.mp3"
  },
  {
    id: "hsk2_041",
    chinese: "快",
    pinyin: "kuài",
    vietnamese: "nhanh",
    english: "fast, quick",
    example: "很快。",
    exampleTranslation: "Rất nhanh.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/kuai.mp3"
  },
  {
    id: "hsk2_042",
    chinese: "慢",
    pinyin: "màn",
    vietnamese: "chậm",
    english: "slow",
    example: "很慢。",
    exampleTranslation: "Rất chậm.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/man.mp3"
  },
  {
    id: "hsk2_043",
    chinese: "高",
    pinyin: "gāo",
    vietnamese: "cao",
    english: "tall, high",
    example: "很高。",
    exampleTranslation: "Rất cao.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/gao.mp3"
  },
  {
    id: "hsk2_044",
    chinese: "矮",
    pinyin: "ǎi",
    vietnamese: "thấp",
    english: "short, low",
    example: "很矮。",
    exampleTranslation: "Rất thấp.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/ai.mp3"
  },
  {
    id: "hsk2_045",
    chinese: "长",
    pinyin: "cháng",
    vietnamese: "dài",
    english: "long",
    example: "很长。",
    exampleTranslation: "Rất dài.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/chang.mp3"
  },
  {
    id: "hsk2_046",
    chinese: "短",
    pinyin: "duǎn",
    vietnamese: "ngắn",
    english: "short",
    example: "很短。",
    exampleTranslation: "Rất ngắn.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/duan.mp3"
  },
  {
    id: "hsk2_047",
    chinese: "新",
    pinyin: "xīn",
    vietnamese: "mới",
    english: "new",
    example: "新车。",
    exampleTranslation: "Xe mới.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/xin.mp3"
  },
  {
    id: "hsk2_048",
    chinese: "旧",
    pinyin: "jiù",
    vietnamese: "cũ",
    english: "old (things)",
    example: "旧书。",
    exampleTranslation: "Sách cũ.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/jiu.mp3"
  },
  {
    id: "hsk2_049",
    chinese: "年轻",
    pinyin: "nián qīng",
    vietnamese: "trẻ",
    english: "young",
    example: "年轻人。",
    exampleTranslation: "Người trẻ.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/nianqing.mp3"
  },
  {
    id: "hsk2_050",
    chinese: "老",
    pinyin: "lǎo",
    vietnamese: "già",
    english: "old (people)",
    example: "老人。",
    exampleTranslation: "Người già.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/lao.mp3"
  },
  {
    id: "hsk2_051",
    chinese: "热",
    pinyin: "rè",
    vietnamese: "nóng",
    english: "hot",
    example: "很热。",
    exampleTranslation: "Rất nóng.",
    topic: "weather",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/re.mp3"
  },
  {
    id: "hsk2_052",
    chinese: "冷",
    pinyin: "lěng",
    vietnamese: "lạnh",
    english: "cold",
    example: "很冷。",
    exampleTranslation: "Rất lạnh.",
    topic: "weather",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/leng.mp3"
  },
  {
    id: "hsk2_053",
    chinese: "漂亮",
    pinyin: "piào liang",
    vietnamese: "đẹp",
    english: "beautiful, pretty",
    example: "很漂亮。",
    exampleTranslation: "Rất đẹp.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/piaoliang.mp3"
  },
  {
    id: "hsk2_054",
    chinese: "聪明",
    pinyin: "cōng ming",
    vietnamese: "thông minh",
    english: "smart, clever",
    example: "很聪明。",
    exampleTranslation: "Rất thông minh.",
    topic: "adjectives",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/congming.mp3"
  },
  {
    id: "hsk2_055",
    chinese: "开心",
    pinyin: "kāi xīn",
    vietnamese: "vui vẻ",
    english: "happy",
    example: "很开心。",
    exampleTranslation: "Rất vui vẻ.",
    topic: "emotions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/kaixin.mp3"
  },
  {
    id: "hsk2_056",
    chinese: "高兴",
    pinyin: "gāo xìng",
    vietnamese: "vui mừng",
    english: "glad, happy",
    example: "很高兴。",
    exampleTranslation: "Rất vui mừng.",
    topic: "emotions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/gaoxing.mp3"
  },
  {
    id: "hsk2_057",
    chinese: "喜欢",
    pinyin: "xǐ huan",
    vietnamese: "thích",
    english: "to like",
    example: "我喜欢你。",
    exampleTranslation: "Tôi thích bạn.",
    topic: "emotions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/xihuan.mp3"
  },
  {
    id: "hsk2_058",
    chinese: "爱",
    pinyin: "ài",
    vietnamese: "yêu",
    english: "to love",
    example: "我爱你。",
    exampleTranslation: "Tôi yêu bạn.",
    topic: "emotions",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/ai.mp3"
  },
  {
    id: "hsk2_059",
    chinese: "想",
    pinyin: "xiǎng",
    vietnamese: "muốn, nghĩ",
    english: "to want, to think",
    example: "我想去。",
    exampleTranslation: "Tôi muốn đi.",
    topic: "verbs",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/xiang.mp3"
  },
  {
    id: "hsk2_060",
    chinese: "觉得",
    pinyin: "jué de",
    vietnamese: "cảm thấy",
    english: "to feel, to think",
    example: "我觉得很好。",
    exampleTranslation: "Tôi cảm thấy rất tốt.",
    topic: "verbs",
    hskLevel: "HSK2",
    difficulty: "beginner",
    audio: "/audio/juede.mp3"
  }
];
