// HSK 3 Vocabulary
export default [
  {
    id: 45,
    chinese: "旅行",
    pinyin: "lǚ xíng",
    vietnamese: "du lịch",
    english: "travel",
    example: "我喜欢旅行。",
    exampleTranslation: "Tôi thích du lịch.",
    topic: "travel",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/luxing.mp3"
  },
  {
    id: 46,
    chinese: "飞机",
    pinyin: "fēi jī",
    vietnamese: "máy bay",
    english: "airplane",
    example: "我坐飞机去北京。",
    exampleTranslation: "Tôi đi máy bay đến Bắc Kinh.",
    topic: "travel",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/feiji.mp3"
  },
  {
    id: 47,
    chinese: "火车",
    pinyin: "huǒ chē",
    vietnamese: "tàu hỏa",
    english: "train",
    example: "火车很快。",
    exampleTranslation: "Tàu hỏa rất nhanh.",
    topic: "travel",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/huoche.mp3"
  },
  {
    id: 48,
    chinese: "汽车",
    pinyin: "qì chē",
    vietnamese: "ô tô",
    english: "car",
    example: "我开车上班。",
    exampleTranslation: "Tôi lái xe đi làm.",
    topic: "travel",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/qiche.mp3"
  },
  {
    id: 49,
    chinese: "自行车",
    pinyin: "zì xíng chē",
    vietnamese: "xe đạp",
    english: "bicycle",
    example: "我喜欢骑自行车。",
    exampleTranslation: "Tôi thích đi xe đạp.",
    topic: "travel",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/zixingche.mp3"
  },
  {
    id: 50,
    chinese: "游泳",
    pinyin: "yóu yǒng",
    vietnamese: "bơi lội",
    english: "swimming",
    example: "夏天我喜欢游泳。",
    exampleTranslation: "Mùa hè tôi thích bơi lội.",
    topic: "sports",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/youyong.mp3"
  },
  {
    id: 51,
    chinese: "跑步",
    pinyin: "pǎo bù",
    vietnamese: "chạy bộ",
    english: "running",
    example: "早上我去跑步。",
    exampleTranslation: "Sáng sớm tôi đi chạy bộ.",
    topic: "sports",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/paobu.mp3"
  },
  {
    id: 52,
    chinese: "踢足球",
    pinyin: "tī zú qiú",
    vietnamese: "đá bóng",
    english: "play football",
    example: "我们踢足球吧。",
    exampleTranslation: "Chúng ta đá bóng nhé.",
    topic: "sports",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/tizuqiu.mp3"
  },
  {
    id: 53,
    chinese: "打篮球",
    pinyin: "dǎ lán qiú",
    vietnamese: "chơi bóng rổ",
    english: "play basketball",
    example: "他很会打篮球。",
    exampleTranslation: "Anh ấy chơi bóng rổ rất giỏi.",
    topic: "sports",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/dalanqiu.mp3"
  },
  {
    id: 54,
    chinese: "音乐",
    pinyin: "yīn yuè",
    vietnamese: "âm nhạc",
    english: "music",
    example: "我喜欢听音乐。",
    exampleTranslation: "Tôi thích nghe nhạc.",
    topic: "entertainment",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/yinyue.mp3"
  },
  {
    id: 55,
    chinese: "电影",
    pinyin: "diàn yǐng",
    vietnamese: "phim",
    english: "movie",
    example: "这部电影很有趣。",
    exampleTranslation: "Bộ phim này rất thú vị.",
    topic: "entertainment",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/dianying.mp3"
  },
  {
    id: 56,
    chinese: "书",
    pinyin: "shū",
    vietnamese: "sách",
    english: "book",
    example: "我在看一本好书。",
    exampleTranslation: "Tôi đang đọc một cuốn sách hay.",
    topic: "entertainment",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/shu.mp3"
  },
  {
    id: 57,
    chinese: "电视",
    pinyin: "diàn shì",
    vietnamese: "tivi",
    english: "television",
    example: "晚上我看电视。",
    exampleTranslation: "Tối tôi xem tivi.",
    topic: "entertainment",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/dianshi.mp3"
  },
  {
    id: 58,
    chinese: "手机",
    pinyin: "shǒu jī",
    vietnamese: "điện thoại",
    english: "mobile phone",
    example: "我的手机坏了。",
    exampleTranslation: "Điện thoại của tôi bị hỏng.",
    topic: "technology",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/shouji.mp3"
  },
  {
    id: 59,
    chinese: "电脑",
    pinyin: "diàn nǎo",
    vietnamese: "máy tính",
    english: "computer",
    example: "我用电脑工作。",
    exampleTranslation: "Tôi dùng máy tính để làm việc.",
    topic: "technology",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/diannao.mp3"
  },
  {
    id: 60,
    chinese: "网络",
    pinyin: "wǎng luò",
    vietnamese: "mạng internet",
    english: "internet, network",
    example: "网络很重要。",
    exampleTranslation: "Mạng internet rất quan trọng.",
    topic: "technology",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/wangluo.mp3"
  },
  {
    id: 61,
    chinese: "天气",
    pinyin: "tiān qì",
    vietnamese: "thời tiết",
    english: "weather",
    example: "今天天气很好。",
    exampleTranslation: "Hôm nay thời tiết rất đẹp.",
    topic: "weather",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/tianqi.mp3"
  },
  {
    id: 62,
    chinese: "春天",
    pinyin: "chūn tiān",
    vietnamese: "mùa xuân",
    english: "spring",
    example: "春天花开了。",
    exampleTranslation: "Mùa xuân hoa nở.",
    topic: "weather",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/chuntian.mp3"
  },
  {
    id: 63,
    chinese: "夏天",
    pinyin: "xià tiān",
    vietnamese: "mùa hè",
    english: "summer",
    example: "夏天很热。",
    exampleTranslation: "Mùa hè rất nóng.",
    topic: "weather",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/xiatian.mp3"
  },
  {
    id: 64,
    chinese: "秋天",
    pinyin: "qiū tiān",
    vietnamese: "mùa thu",
    english: "autumn",
    example: "秋天叶子黄了。",
    exampleTranslation: "Mùa thu lá cây vàng.",
    topic: "weather",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/qiutian.mp3"
  },
  {
    id: 65,
    chinese: "冬天",
    pinyin: "dōng tiān",
    vietnamese: "mùa đông",
    english: "winter",
    example: "冬天下雪了。",
    exampleTranslation: "Mùa đông tuyết rơi.",
    topic: "weather",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/dongtian.mp3"
  },
  {
    id: 66,
    chinese: "健康",
    pinyin: "jiàn kāng",
    vietnamese: "sức khỏe",
    english: "health",
    example: "健康最重要。",
    exampleTranslation: "Sức khỏe là quan trọng nhất.",
    topic: "health",
    hskLevel: "HSK3",
    difficulty: "intermediate",
    audio: "/audio/jiankang.mp3"
  }
];
