// HSK 4 Vocabulary
export default [
  {
    id: 67,
    chinese: "经验",
    pinyin: "jīng yàn",
    vietnamese: "kinh nghiệm",
    english: "experience",
    example: "他有很多工作经验。",
    exampleTranslation: "Anh ấy có rất nhiều kinh nghiệm làm việc.",
    topic: "work",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/jingyan.mp3"
  },
  {
    id: 68,
    chinese: "机会",
    pinyin: "jī huì",
    vietnamese: "cơ hội",
    english: "opportunity",
    example: "这是一个好机会。",
    exampleTranslation: "Đây là một cơ hội tốt.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/jihui.mp3"
  },
  {
    id: 69,
    chinese: "文化",
    pinyin: "wén huà",
    vietnamese: "văn hóa",
    english: "culture",
    example: "中国文化很有趣。",
    exampleTranslation: "Văn hóa Trung Quốc rất thú vị.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/wenhua.mp3"
  },
  {
    id: 70,
    chinese: "历史",
    pinyin: "lì shǐ",
    vietnamese: "lịch sử",
    english: "history",
    example: "我喜欢学习历史。",
    exampleTranslation: "Tôi thích học lịch sử.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/lishi.mp3"
  },
  {
    id: 71,
    chinese: "社会",
    pinyin: "shè huì",
    vietnamese: "xã hội",
    english: "society",
    example: "社会在不断发展。",
    exampleTranslation: "Xã hội không ngừng phát triển.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/shehui.mp3"
  },
  {
    id: 72,
    chinese: "政府",
    pinyin: "zhèng fǔ",
    vietnamese: "chính phủ",
    english: "government",
    example: "政府制定了新政策。",
    exampleTranslation: "Chính phủ đã đưa ra chính sách mới.",
    topic: "politics",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/zhengfu.mp3"
  },
  {
    id: 73,
    chinese: "法律",
    pinyin: "fǎ lǜ",
    vietnamese: "pháp luật",
    english: "law",
    example: "我们要遵守法律。",
    exampleTranslation: "Chúng ta phải tuân thủ pháp luật.",
    topic: "politics",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/falv.mp3"
  },
  {
    id: 74,
    chinese: "科学",
    pinyin: "kē xué",
    vietnamese: "khoa học",
    english: "science",
    example: "科学技术很重要。",
    exampleTranslation: "Khoa học công nghệ rất quan trọng.",
    topic: "science",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/kexue.mp3"
  },
  {
    id: 75,
    chinese: "技术",
    pinyin: "jì shù",
    vietnamese: "công nghệ",
    english: "technology",
    example: "现代技术发展很快。",
    exampleTranslation: "Công nghệ hiện đại phát triển rất nhanh.",
    topic: "science",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/jishu.mp3"
  },
  {
    id: 76,
    chinese: "环境",
    pinyin: "huán jìng",
    vietnamese: "môi trường",
    english: "environment",
    example: "保护环境很重要。",
    exampleTranslation: "Bảo vệ môi trường rất quan trọng.",
    topic: "environment",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/huanjing.mp3"
  },
  {
    id: 77,
    chinese: "自然",
    pinyin: "zì rán",
    vietnamese: "tự nhiên",
    english: "nature",
    example: "我喜欢自然的美景。",
    exampleTranslation: "Tôi thích cảnh đẹp tự nhiên.",
    topic: "environment",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/ziran.mp3"
  },
  {
    id: 78,
    chinese: "发展",
    pinyin: "fā zhǎn",
    vietnamese: "phát triển",
    english: "development",
    example: "这个城市发展很快。",
    exampleTranslation: "Thành phố này phát triển rất nhanh.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/fazhan.mp3"
  },
  {
    id: 79,
    chinese: "改变",
    pinyin: "gǎi biàn",
    vietnamese: "thay đổi",
    english: "change",
    example: "时代在改变。",
    exampleTranslation: "Thời đại đang thay đổi.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/gaibian.mp3"
  },
  {
    id: 80,
    chinese: "进步",
    pinyin: "jìn bù",
    vietnamese: "tiến bộ",
    english: "progress",
    example: "我们取得了很大进步。",
    exampleTranslation: "Chúng ta đã đạt được tiến bộ lớn.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/jinbu.mp3"
  },
  {
    id: 81,
    chinese: "成功",
    pinyin: "chéng gōng",
    vietnamese: "thành công",
    english: "success",
    example: "努力工作会成功。",
    exampleTranslation: "Làm việc chăm chỉ sẽ thành công.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/chenggong.mp3"
  },
  {
    id: 82,
    chinese: "失败",
    pinyin: "shī bài",
    vietnamese: "thất bại",
    english: "failure",
    example: "失败是成功之母。",
    exampleTranslation: "Thất bại là mẹ của thành công.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/shibai.mp3"
  },
  {
    id: 83,
    chinese: "困难",
    pinyin: "kùn nán",
    vietnamese: "khó khăn",
    english: "difficulty",
    example: "遇到困难要坚持。",
    exampleTranslation: "Gặp khó khăn phải kiên trì.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/kunnan.mp3"
  },
  {
    id: 84,
    chinese: "解决",
    pinyin: "jiě jué",
    vietnamese: "giải quyết",
    english: "solve",
    example: "我们要解决这个问题。",
    exampleTranslation: "Chúng ta phải giải quyết vấn đề này.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/jiejue.mp3"
  },
  {
    id: 85,
    chinese: "创造",
    pinyin: "chuàng zào",
    vietnamese: "sáng tạo",
    english: "create",
    example: "我们要创造新的机会。",
    exampleTranslation: "Chúng ta phải tạo ra cơ hội mới.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/chuangzao.mp3"
  },
  {
    id: 86,
    chinese: "建设",
    pinyin: "jiàn shè",
    vietnamese: "xây dựng",
    english: "build, construct",
    example: "建设美好的未来。",
    exampleTranslation: "Xây dựng tương lai tươi đẹp.",
    topic: "abstract",
    hskLevel: "HSK4",
    difficulty: "intermediate",
    audio: "/audio/jianshe.mp3"
  }
];
