const hsk5 = [
  {
    id: 87,
    chinese: "挑战",
    pinyin: "tiǎo zhàn",
    vietnamese: "thử thách",
    english: "challenge",
    example: "这是一个很大的挑战。",
    exampleTranslation: "Đây là một thử thách rất lớn.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/tiaozhan.mp3"
  },
  {
    id: 88,
    chinese: "竞争",
    pinyin: "jìng zhēng",
    vietnamese: "cạnh tranh",
    english: "competition",
    example: "市场竞争很激烈。",
    exampleTranslation: "Cạnh tranh thị trường rất khốc liệt.",
    topic: "business",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/jingzheng.mp3"
  },
  {
    id: 89,
    chinese: "合作",
    pinyin: "hé zuò",
    vietnamese: "hợp tác",
    english: "cooperation",
    example: "国际合作很重要。",
    exampleTranslation: "Hợp tác quốc tế rất quan trọng.",
    topic: "business",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/hezuo.mp3"
  },
  {
    id: 90,
    chinese: "投资",
    pinyin: "tóu zī",
    vietnamese: "đầu tư",
    english: "investment",
    example: "这是一个好的投资。",
    exampleTranslation: "Đây là một khoản đầu tư tốt.",
    topic: "business",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/touzi.mp3"
  },
  {
    id: 91,
    chinese: "经济",
    pinyin: "jīng jì",
    vietnamese: "kinh tế",
    english: "economy",
    example: "经济发展很快。",
    exampleTranslation: "Kinh tế phát triển rất nhanh.",
    topic: "business",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/jingji.mp3"
  },
  {
    id: 92,
    chinese: "市场",
    pinyin: "shì chǎng",
    vietnamese: "thị trường",
    english: "market",
    example: "这个市场很大。",
    exampleTranslation: "Thị trường này rất lớn.",
    topic: "business",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/shichang.mp3"
  },
  {
    id: 93,
    chinese: "企业",
    pinyin: "qǐ yè",
    vietnamese: "doanh nghiệp",
    english: "enterprise",
    example: "他创办了一家企业。",
    exampleTranslation: "Anh ấy đã thành lập một doanh nghiệp.",
    topic: "business",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/qiye.mp3"
  },
  {
    id: 94,
    chinese: "管理",
    pinyin: "guǎn lǐ",
    vietnamese: "quản lý",
    english: "management",
    example: "好的管理很重要。",
    exampleTranslation: "Quản lý tốt rất quan trọng.",
    topic: "business",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/guanli.mp3"
  },
  {
    id: 95,
    chinese: "责任",
    pinyin: "zé rèn",
    vietnamese: "trách nhiệm",
    english: "responsibility",
    example: "这是我的责任。",
    exampleTranslation: "Đây là trách nhiệm của tôi.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/zeren.mp3"
  },
  {
    id: 96,
    chinese: "权利",
    pinyin: "quán lì",
    vietnamese: "quyền lợi",
    english: "rights",
    example: "每个人都有自己的权利。",
    exampleTranslation: "Mỗi người đều có quyền lợi của mình.",
    topic: "politics",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/quanli.mp3"
  },
  {
    id: 97,
    chinese: "义务",
    pinyin: "yì wù",
    vietnamese: "nghĩa vụ",
    english: "obligation",
    example: "这是公民的义务。",
    exampleTranslation: "Đây là nghĩa vụ của công dân.",
    topic: "politics",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/yiwu.mp3"
  },
  {
    id: 98,
    chinese: "自由",
    pinyin: "zì yóu",
    vietnamese: "tự do",
    english: "freedom",
    example: "自由很珍贵。",
    exampleTranslation: "Tự do rất quý giá.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/ziyou.mp3"
  },
  {
    id: 99,
    chinese: "平等",
    pinyin: "píng děng",
    vietnamese: "bình đẳng",
    english: "equality",
    example: "人人生而平等。",
    exampleTranslation: "Con người sinh ra đều bình đẳng.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/pingdeng.mp3"
  },
  {
    id: 100,
    chinese: "和谐",
    pinyin: "hé xié",
    vietnamese: "hòa hợp",
    english: "harmony",
    example: "社会需要和谐。",
    exampleTranslation: "Xã hội cần sự hòa hợp.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/hexie.mp3"
  },
  {
    id: 101,
    chinese: "创新",
    pinyin: "chuàng xīn",
    vietnamese: "đổi mới",
    english: "innovation",
    example: "创新推动发展。",
    exampleTranslation: "Đổi mới thúc đẩy phát triển.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/chuangxin.mp3"
  },
  {
    id: 102,
    chinese: "效率",
    pinyin: "xiào lǜ",
    vietnamese: "hiệu quả",
    english: "efficiency",
    example: "提高工作效率。",
    exampleTranslation: "Nâng cao hiệu quả công việc.",
    topic: "work",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/xiaolv.mp3"
  },
  {
    id: 103,
    chinese: "质量",
    pinyin: "zhì liàng",
    vietnamese: "chất lượng",
    english: "quality",
    example: "质量比数量重要。",
    exampleTranslation: "Chất lượng quan trọng hơn số lượng.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/zhiliang.mp3"
  },
  {
    id: 104,
    chinese: "标准",
    pinyin: "biāo zhǔn",
    vietnamese: "tiêu chuẩn",
    english: "standard",
    example: "这是国际标准。",
    exampleTranslation: "Đây là tiêu chuẩn quốc tế.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/biaozhun.mp3"
  },
  {
    id: 105,
    chinese: "理想",
    pinyin: "lǐ xiǎng",
    vietnamese: "lý tưởng",
    english: "ideal",
    example: "每个人都有理想。",
    exampleTranslation: "Mỗi người đều có lý tưởng.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/lixiang.mp3"
  },
  {
    id: 106,
    chinese: "现实",
    pinyin: "xiàn shí",
    vietnamese: "thực tế",
    english: "reality",
    example: "理想和现实有差距。",
    exampleTranslation: "Lý tưởng và thực tế có khoảng cách.",
    topic: "abstract",
    hskLevel: "HSK5",
    difficulty: "advanced",
    audio: "/audio/xianshi.mp3"
  }
];

export default hsk5;
